name: CI Build
on: [ pull_request ]
jobs:
  Build_and_test:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: add MSBuild to path
        uses: microsoft/setup-msbuild@v1.0.3
        
      - name: build code
        run: msbuild.exe ./src/WindowsTestHelpers.sln /restore -p:Configuration=Release
        
      - name: setup tests
        uses: darenm/Setup-VSTest@v1
        
      - name: run tests
        run: vstest.console.exe ../WindowsTestHelpers.dll
   
